### ISSUE TITLE
Crop Disease Classification - Agriculture Domain TASK LIST

### ISSUE THREAD

**Issue by VikramjitSinghRathee** [VikramjitSinghRathee/Finetuning-with-Pre_Trained-Mobilenet_v2-for-Crop-Disease-Classification---Agriculture-Domain#1]
- [ ] (a) Deploy ML WebApp
- [ ] (b) Utilize Tensorflow Lite model and deploy mobile app

# Further down the line
- [ ] Train models for other crops and Revisit (a) and (b)
